server:
  port: 8080
  servlet:
    context-path: /api/v1

spring:
  application:
    name: fitlife-api

  datasource:
    url: jdbc:mysql://localhost:3306/fitlife_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

cloudinary:
  cloud-name: "dvseaoy5k"
  api-key: "548378961766311"
  api-secret: "GqtAOdXDUzX9sY5Eqg6LWrb_oKU"

gemini:
  api-key: "AIzaSyDxDDuK3_-S0GHPgr7lkqL1fCcHLybux8Q"
  api-url: "https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent"

# ĐÃ KÉO RA NGOÀI CÙNG LỀ TRÁI NGANG VỚI GEMINI
vnpay:
  tmn-code: BSHJNZHW
  hash-secret: SG3U8HBZ5KDAH3UN7PDIA4DY3GFNKQF3
  pay-url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/v1/payment/vnpay-return