server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitlife_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: 012140268Pp # Lưu ý: Đừng commit dòng mật khẩu này lên public GitHub nhé!

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: nguyenkhanh7510@gmail.com
    password: 012140268Pp
    # Thêm cấu hình properties bắt buộc để Spring Mail có thể gửi được qua Mailtrap
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: demo_cloud_name
  api-key: 123456789012345
  api-secret: abcdefghijklmnopqrstuvwxyz123456

google:
  enabled: false
  client-id: 1234567890-abcdefghijklmnopqrstuvwxyz.apps.googleusercontent.com

gemini:
  enabled: false # Đã sửa từ 'failse'
  api-key: AIzaSyB_abcdefghijklmnopqrstuvwxyz1234

vnpay:
  enabled: false
  # Mình thêm sẵn các cấu hình chuẩn thường dùng của VNPay Sandbox để sau này bạn dùng luôn
  tmn-code: QWERTYUI
  hash-secret: ABCDEFGHIJKLMNOPQRSTUVWXYZ123456
  url: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  return-url: http://localhost:8080/api/payment/vnpay-return

application:
  security:
    jwt:
      secret: MDEyMzQ1Njc4OWFiY2RlZjAxMjM0NTY3ODlhYmNkZWYwMTIzNDU2Nzg5YWJjZGVmMDEyMzQ1Njc4OWFiY2RlZg==
      expiration-ms: 86400000 # Mình thêm 2 số 0 vào cuối (86,400,000 ms = 24 giờ) vì 864000 ms chỉ được có 14 phút thôi.