-- =========================================================
-- V21__seed_ai_knowledge.sql
-- Knowledge source cho FitLife AI RAG
-- =========================================================

INSERT INTO ai_knowledge (
    code,
    title,
    content,
    category,
    goal,
    experience_level,
    language,
    active,
    index_status,
    qdrant_point_id,
    indexed_at,
    index_error,
    is_deleted,
    created_at,
    updated_at
)
VALUES
    (
        'WORKOUT_LOSE_WEIGHT_BEGINNER_VI',
        'Tập luyện giảm cân cho người mới',
        'Người mới giảm cân nên kết hợp tập sức mạnh toàn thân và cardio mức vừa phải. Có thể bắt đầu từ ba buổi mỗi tuần, ưu tiên kỹ thuật đúng và tăng khối lượng tập từ từ. Không cần tập kiệt sức trong mỗi buổi.',
        'WORKOUT',
        'LOSE_WEIGHT',
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'WORKOUT_GAIN_MUSCLE_BEGINNER_VI',
        'Tập luyện tăng cơ cho người mới',
        'Người mới tăng cơ nên ưu tiên bài tập nền tảng, kỹ thuật đúng và tăng tải có kiểm soát. Phần lớn bài tập có thể sử dụng từ hai đến bốn hiệp, tám đến mười lăm lần lặp và nghỉ từ sáu mươi đến một trăm hai mươi giây.',
        'WORKOUT',
        'GAIN_MUSCLE',
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'WORKOUT_SAFETY_BEGINNER_VI',
        'An toàn tập luyện cho người mới',
        'Khởi động từ năm đến mười phút trước buổi tập. Dừng tập khi xuất hiện đau nhói, chóng mặt, khó thở bất thường hoặc mất kiểm soát kỹ thuật. Người có vấn đề sức khỏe nên tham khảo bác sĩ hoặc huấn luyện viên chuyên môn.',
        'SAFETY',
        NULL,
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'WORKOUT_RECOVERY_BEGINNER_VI',
        'Phục hồi sau tập cho người mới',
        'Phục hồi cần bao gồm ngủ đủ, ăn uống phù hợp và bố trí ngày nghỉ. Không nên tập nặng cùng một nhóm cơ liên tục khi chưa phục hồi. Đau cơ nhẹ có thể bình thường, nhưng đau khớp hoặc đau nhói cần được theo dõi.',
        'RECOVERY',
        NULL,
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'NUTRITION_LOSE_WEIGHT_BEGINNER_VI',
        'Dinh dưỡng giảm cân an toàn',
        'Giảm cân nên sử dụng mức thâm hụt năng lượng vừa phải. Mỗi bữa ưu tiên protein, rau xanh, thực phẩm ít chế biến và khẩu phần tinh bột phù hợp. Không nên nhịn đói kéo dài hoặc áp dụng mức cắt giảm cực đoan.',
        'NUTRITION',
        'LOSE_WEIGHT',
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'NUTRITION_GAIN_MUSCLE_BEGINNER_VI',
        'Dinh dưỡng hỗ trợ tăng cơ',
        'Tăng cơ cần đủ năng lượng, protein và lịch tập có tiến triển. Nguồn protein phổ biến gồm trứng, thịt gà, cá, thịt nạc, sữa, sữa chua và đậu hũ. Có thể phân bổ protein qua nhiều bữa trong ngày.',
        'NUTRITION',
        'GAIN_MUSCLE',
        'BEGINNER',
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'NUTRITION_VIETNAMESE_MEALS_VI',
        'Bữa ăn Việt Nam cân bằng',
        'Một bữa ăn thực tế có thể gồm cơm với khẩu phần phù hợp, thịt hoặc cá, rau xanh và canh. Ưu tiên hấp, luộc hoặc áp chảo ít dầu. Hạn chế nước ngọt và thực phẩm chiên nhiều dầu sử dụng thường xuyên.',
        'NUTRITION',
        NULL,
        NULL,
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'BODY_METRIC_BMI_REFERENCE_VI',
        'Ý nghĩa tham khảo của BMI',
        'BMI là chỉ số sàng lọc dựa trên chiều cao và cân nặng. Chỉ số này không phân biệt đầy đủ khối cơ và khối mỡ. Nên kết hợp BMI với vòng eo, tỷ lệ mỡ, hình ảnh tiến độ và hiệu suất tập luyện.',
        'BODY_METRIC',
        NULL,
        NULL,
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'BODY_METRIC_PROGRESS_VI',
        'Theo dõi tiến độ cơ thể',
        'Không nên đánh giá tiến độ chỉ bằng một lần đo. Cần theo dõi cân nặng, vòng eo, hình ảnh và hiệu suất tập luyện trong nhiều tuần, trong điều kiện đo tương đối giống nhau.',
        'BODY_METRIC',
        NULL,
        NULL,
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        'GENERAL_HEALTH_SAFETY_VI',
        'Cảnh báo sức khỏe chung',
        'Các gợi ý của FitLife chỉ mang tính tham khảo và không thay thế chẩn đoán y tế. Người có bệnh nền, chấn thương, đang mang thai hoặc có triệu chứng bất thường nên tham khảo nhân viên y tế trước khi áp dụng kế hoạch.',
        'SAFETY',
        NULL,
        NULL,
        'vi',
        TRUE,
        'PENDING',
        NULL,
        NULL,
        NULL,
        FALSE,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );