### ============================================================
### AUTH MANUAL TEST
### Mailtrap / OTP / Google
### Chạy từng request
### ============================================================


### 1. Verify email manually
### Điền verificationToken trong private env
GET {{baseUrl}}/auth/verify-email?token={{verificationToken}}
Accept: application/json


### 2. Login after verification
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "{{authRegisterUsername}}",
  "password": "12345678"
}


### 3. Forgot password
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
  "email": "{{authRegisterEmail}}"
}


### 4. Reset password manually
### Điền resetOtp trong private env
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "email": "{{authRegisterEmail}}",
  "otp": "{{resetOtp}}",
  "newPassword": "NewPassword123",
  "confirmPassword": "NewPassword123"
}


### 5. Login with new password
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "{{authRegisterUsername}}",
  "password": "NewPassword123"
}


### 6. Google login manually
### Điền ID token thật
POST {{baseUrl}}/auth/google-login
Content-Type: application/json
Accept: application/json

{
  "idToken": "{{googleIdToken}}"
}