
### Admin get member list
GET {{baseUrl}}/admin/members?page=1&size=10&keyword=member&status=ACTIVE
Accept: application/json
Authorization: Bearer {{accessToken}}

### Admin create member
POST {{baseUrl}}/admin/members
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "hoivien_fitlife_1011",
  "email": "fitlife101@gmail.com",
  "password": "password123",
  "fullName": "Nguyễn Văn Hội Viên 101",
  "phone": "0912345611",
  "gender": "MALE",
  "dateOfBirth": "1998-05-20",
  "address": "Hà Nội",
  "emergencyContactName": "Nguyễn Văn A",
  "emergencyContactPhone": "0900000000",
  "fitnessGoal": "LOSE_WEIGHT",
  "healthNote": "Không có bệnh nền"
}

### Admin get member detail
GET {{baseUrl}}/admin/members/1
Accept: application/json
Authorization: Bearer {{accessToken}}

### Admin get member by code
GET {{baseUrl}}/admin/members/code/MEM001
Accept: application/json
Authorization: Bearer {{accessToken}}

### Admin update member
PUT {{baseUrl}}/admin/members/1
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "fullName": "Nguyễn Văn Hội Viên Sau Sửa",
  "email": "fitlife99_updated@gmail.com",
  "phone": "0999888777",
  "gender": "FEMALE",
  "dateOfBirth": "1998-05-20",
  "address": "TP.HCM",
  "emergencyContactName": "Nguyễn Văn B",
  "emergencyContactPhone": "0911111111",
  "fitnessGoal": "GAIN_MUSCLE",
  "healthNote": "Muốn tăng cơ",
  "status": "ACTIVE"
}

### Admin update status
PATCH {{baseUrl}}/admin/members/1/status
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{accessToken}}

{
  "status": "ACTIVE"
}

### Admin soft delete member
DELETE {{baseUrl}}/admin/members/1
Authorization: Bearer {{accessToken}}

### Admin restore member
PATCH {{baseUrl}}/admin/members/1/restore
Authorization: Bearer {{accessToken}}

