### Register Member
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "password": "123456",
  "fullName": "Member 01",
  "phone": "0900000001"
}


### Login Member and save token
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "password": "123456"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}


### Login with wrong password
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "password": "wrongpassword"
}


### Register duplicate email
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "password": "123456",
  "fullName": "Member Duplicate",
  "phone": "0900000002"
}


### Register validation failed
POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "",
  "password": "123",
  "fullName": "",
  "phone": "0900000003"
}