### =========================

### AUTH API TEST

### Base URL: {{baseUrl}}

### Contenxt path: /auth/v1

### =========================

### 1. Register Member 01 - success

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "Tram01",
  "email": "Tram01@gmail.com",
  "password": "123456",
  "fullName": "Tram 01",
  "phone": "0000000777"
}

### 2. Login Member 02 by email and save token - success

POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "Tram01@gmail.com",
  "password": "123456"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}

### 3. Login Member 02 by username and save token - success

POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "member02",
  "password": "123456"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 4. Login with wrong password - should fail

POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "member01@gmail.com",
  "password": "wrongpassword"
}

### 5. Login with unknown identifier - should fail

POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "unknown_member",
  "password": "123456"
}

### 6. Register duplicate username - should fail

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "member01",
  "email": "member01_new@gmail.com",
  "password": "123456",
  "fullName": "Member Duplicate Username",
  "phone": "0900000099"
}

### 7. Register duplicate email - should fail

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "member_duplicate_email",
  "email": "[member01@gmail.com](mailto:member01@gmail.com)",
  "password": "123456",
  "fullName": "Member Duplicate Email",
  "phone": "0999999999"
}

### 8. Register duplicate phone - should fail

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "newmember",
  "email": "[newmember@gmail.com](mailto:newmember@gmail.com)",
  "password": "123456",
  "fullName": "Member Duplicate Phone",
  "phone": "0900000001"
}

### 9. Register validation failed - should fail

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "",
  "email": "",
  "password": "123",
  "fullName": "",
  "phone": "0900000003"
}






### 10. Register Admin 02 - success

POST {{baseUrl}}/auth/register
Content-Type: application/json
Accept: application/json

{
  "username": "admin02",
  "email": "admin02@fitlife.local",
  "password": "765123",
  "fullName": "FitLife Admin 02",
  "phone": "0911223344"
}


### 11. Login Admin bằng tài khoản Seed mẫu (V2) - success
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "admin02",
  "password": "765123"
}

> {%
    // Lưu riêng token đặc quyền để tránh ghi đè lên biến accessToken của hội viên
    client.global.set("adminToken", response.body.data.accessToken);
%}


### 12. Login Admin 02 mới đăng ký (Sau khi đã gán quyền trong DB) - success
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "admin02",
  "password": "password123"
}

> {%
    client.global.set("adminToken", response.body.data.accessToken);
%}


### 13. M03 - Admin xem danh sách hội viên phân trang, tìm kiếm - success
GET {{baseUrl}}/admin/members?page=1&size=10&keyword=Tram&status=ACTIVE
Accept: application/json
Authorization: Bearer {{adminToken}}


### 14. M04 - Admin xem thông tin chi tiết một hội viên theo ID - success
GET {{baseUrl}}/admin/members/1
Accept: application/json
Authorization: Bearer {{adminToken}}




