### =========================
### PASSWORD RESET API TEST
### Base URL: {{baseUrl}}
### =========================


### 1. Forgot password - send reset token to email
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
  "email": "member02@gmail.com"
}


### 2. Reset password - replace resetToken manually from email/Mailtrap
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "resetToken": "99cf9ace-6cb7-4207-80a4-eac36562082f",
  "newPassword": "654321",
  "confirmPassword": "654321"
}


### 3. Login with new password - should success
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "member01",
  "password": "654321"
}

> {%
    client.global.set("accessToken", response.body.data.accessToken);
%}


### 4. Reset password with invalid token - should fail
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "resetToken": "invalid-token",
  "newPassword": "123456",
  "confirmPassword": "123456"
}


### 5. Reset password with confirm mismatch - should fail
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "resetToken": "paste-reset-token-here",
  "newPassword": "123456",
  "confirmPassword": "wrong-confirm"
}


### 6. Forgot password validation failed - should fail
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
  "email": ""
}


### 7. Reset password validation failed - should fail
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "resetToken": "",
  "newPassword": "123",
  "confirmPassword": ""
}