
### 1. Forgot password - send OTP
POST {{baseUrl}}/auth/forgot-password
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com"
}


### 2. Reset password using OTP
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "otp": "754919",
  "newPassword": "654321",
  "confirmPassword": "654321"
}


### 3. Login with new password
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "member01",
  "password": "654321"
}


### 4. Login with old password - should fail
POST {{baseUrl}}/auth/login
Content-Type: application/json
Accept: application/json

{
  "identifier": "member01",
  "password": "123456"
}


### 5. Reset password with wrong OTP - should fail
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "otp": "000000",
  "newPassword": "123456",
  "confirmPassword": "123456"
}


### 6. Reset password confirm mismatch - should fail
POST {{baseUrl}}/auth/reset-password
Content-Type: application/json
Accept: application/json

{
  "email": "member01@gmail.com",
  "otp": "754919",
  "newPassword": "123456",
  "confirmPassword": "wrong"
}