### Test Swagger endpoint nếu có test controller
GET {{baseUrl}}/test/swagger
Accept: application/json


### Test roles nếu có TestRoleUserController
GET {{baseUrl}}/test/roles
Accept: application/json


### Test create user nếu có TestRoleUserController
GET {{baseUrl}}/test/create-user
Accept: application/json