### Login as admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "123456"
}

> {%
    client.global.set("admin_token", response.body.data.accessToken);
%}


### Get current user
GET {{baseUrl}}/users/me
Authorization: Bearer {{admin_token}}


### Admin - Get all users
GET {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}


### Admin - Get users with pagination
GET {{baseUrl}}/admin/users?page=0&size=10
Authorization: Bearer {{admin_token}}


### Admin - Search users by keyword
GET {{baseUrl}}/admin/users?keyword=huy
Authorization: Bearer {{admin_token}}


### Admin - Filter users by role
GET {{baseUrl}}/admin/users?roleCode=ROLE_MEMBER
Authorization: Bearer {{admin_token}}


### Admin - Filter users by status
GET {{baseUrl}}/admin/users?status=ACTIVE
Authorization: Bearer {{admin_token}}


### Admin - Search + filter + pagination
GET {{baseUrl}}/admin/users?page=0&size=5&keyword=huy&roleCode=ROLE_MEMBER&status=ACTIVE
Authorization: Bearer {{admin_token}}


### Admin - Invalid status
GET {{baseUrl}}/admin/users?status=ABC
Authorization: Bearer {{admin_token}}

### Admin - Get user detail by id
GET {{baseUrl}}/admin/users/1
Authorization: Bearer {{admin_token}}


### Admin - Get user detail not found
GET {{baseUrl}}/admin/users/999999
Authorization: Bearer {{admin_token}}


### Admin - Get user detail without token
GET {{baseUrl}}/admin/users/1


### Admin - Get user detail with invalid id format
GET {{baseUrl}}/admin/users/abc
Authorization: Bearer {{admin_token}}

### Admin - Create internal Staff account
POST {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "staff02",
  "email": "staff02@fitlife.local",
  "password": "123456",
  "fullName": "FitLife Staff 02",
  "phone": "0900000022",
  "roleCode": "ROLE_STAFF",
  "status": "ACTIVE"
}

### Admin - Create internal Trainer account
POST {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "trainer02",
  "email": "trainer02@fitlife.local",
  "password": "123456",
  "fullName": "FitLife Trainer 02",
  "phone": "0900000032",
  "roleCode": "ROLE_TRAINER",
  "status": "ACTIVE"
}

### Admin - Create internal user with MEMBER role should fail
POST {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "member02",
  "email": "member02@fitlife.local",
  "password": "123456",
  "fullName": "FitLife Member 02",
  "phone": "0900000042",
  "roleCode": "ROLE_MEMBER",
  "status": "ACTIVE"
}

### Admin - Create internal user duplicate email
POST {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "staff03",
  "email": "staff02@fitlife.local",
  "password": "123456",
  "fullName": "FitLife Staff 03",
  "phone": "0900000023",
  "roleCode": "ROLE_STAFF",
  "status": "ACTIVE"
}

### Admin - Create internal user without token
POST {{baseUrl}}/admin/users
Content-Type: application/json

{
  "username": "staff04",
  "email": "staff04@fitlife.local",
  "password": "123456",
  "fullName": "FitLife Staff 04",
  "phone": "0900000024",
  "roleCode": "ROLE_STAFF",
  "status": "ACTIVE"
}

### Admin - Update user information
PUT {{baseUrl}}/admin/users/5
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "username": "staff02_updated",
  "email": "staff02.updated@fitlife.local",
  "fullName": "FitLife Staff 02 Updated",
  "phone": "0900000099",
  "status": "ACTIVE"
}

### Admin - Update user full name only
PUT {{baseUrl}}/admin/users/5
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "fullName": "FitLife Staff Updated Name"
}

### Admin - Update user not found
PUT {{baseUrl}}/admin/users/999999
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "fullName": "Not Found User"
}

### Admin - Update duplicate email
PUT {{baseUrl}}/admin/users/5
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "email": "admin@fitlife.local"
}

### Admin - Update invalid status
PUT {{baseUrl}}/admin/users/5
Authorization: Bearer {{admin_token}}
Content-Type: application/json

{
  "status": "ABC"
}


### Admin - Update user without token
PUT {{baseUrl}}/admin/users/5
Content-Type: application/json

{
  "fullName": "No Token"
}

