### Login as admin
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "identifier": "admin",
  "password": "123456"
}

> {%
    client.global.set("admin_token", response.body.data.accessToken);
%}


### Get current user
GET {{baseUrl}}/users/me
Authorization: Bearer {{admin_token}}


### Admin - Get all users
GET {{baseUrl}}/admin/users
Authorization: Bearer {{admin_token}}


### Admin - Get users with pagination
GET {{baseUrl}}/admin/users?page=0&size=10
Authorization: Bearer {{admin_token}}


### Admin - Search users by keyword
GET {{baseUrl}}/admin/users?keyword=huy
Authorization: Bearer {{admin_token}}


### Admin - Filter users by role
GET {{baseUrl}}/admin/users?roleCode=ROLE_MEMBER
Authorization: Bearer {{admin_token}}


### Admin - Filter users by status
GET {{baseUrl}}/admin/users?status=ACTIVE
Authorization: Bearer {{admin_token}}


### Admin - Search + filter + pagination
GET {{baseUrl}}/admin/users?page=0&size=5&keyword=huy&roleCode=ROLE_MEMBER&status=ACTIVE
Authorization: Bearer {{admin_token}}


### Admin - Invalid status
GET {{baseUrl}}/admin/users?status=ABC
Authorization: Bearer {{admin_token}}

### Admin - Get user detail by id
GET {{baseUrl}}/admin/users/1
Authorization: Bearer {{admin_token}}


### Admin - Get user detail not found
GET {{baseUrl}}/admin/users/999999
Authorization: Bearer {{admin_token}}


### Admin - Get user detail without token
GET {{baseUrl}}/admin/users/1


### Admin - Get user detail with invalid id format
GET {{baseUrl}}/admin/users/abc
Authorization: Bearer {{admin_token}}